// Este archivo es generado automáticamente. No editar manualmente.
export const idsChips = [
  {
    title: "BACKSPACE",
    title_text: "BACKSPACE",
    text: <>Constante numérica 8 para la tecla backspace.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "TAB",
    title_text: "TAB",
    text: <>Constante numérica 9 para la tecla tab.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "ENTER",
    title_text: "ENTER",
    text: <>Constante numérica 13 para la tecla enter.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "SHIFT",
    title_text: "SHIFT",
    text: <>Constante numérica 16 para la tecla shift.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "CONTROL",
    title_text: "CONTROL",
    text: <>Constante numérica 17 para la tecla control.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "ALT",
    title_text: "ALT",
    text: <>Constante numérica 18 para la tecla alt.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "PAUSE",
    title_text: "PAUSE",
    text: <>Constante numérica 19 para la tecla pause.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "CAPS_LOCK",
    title_text: "CAPS_LOCK",
    text: <>Constante numérica 20 para la tecla caps lock.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "ESCAPE",
    title_text: "ESCAPE",
    text: <>Constante numérica 27 para la tecla escape.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "SPACE",
    title_text: "SPACE",
    text: <>Constante numérica 32 para la tecla space.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "PAGE_UP",
    title_text: "PAGE_UP",
    text: <>Constante numérica 33 para la tecla page up.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "PAGE_DOWN",
    title_text: "PAGE_DOWN",
    text: <>Constante numérica 34 para la tecla page down.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "END",
    title_text: "END",
    text: <>Constante numérica 35 para la tecla end.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "HOME",
    title_text: "HOME",
    text: <>Constante numérica 36 para la tecla home.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "ARROW_LEFT",
    title_text: "ARROW_LEFT",
    text: <>Constante numérica 37 para la tecla arrow left.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "ARROW_UP",
    title_text: "ARROW_UP",
    text: <>Constante numérica 38 para la tecla arrow up.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "ARROW_RIGHT",
    title_text: "ARROW_RIGHT",
    text: <>Constante numérica 39 para la tecla arrow right.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "ARROW_DOWN",
    title_text: "ARROW_DOWN",
    text: <>Constante numérica 40 para la tecla arrow down.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "PRINT_SCREEN",
    title_text: "PRINT_SCREEN",
    text: <>Constante numérica 44 para la tecla print screen.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "INSERT",
    title_text: "INSERT",
    text: <>Constante numérica 45 para la tecla insert.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "DELETE",
    title_text: "DELETE",
    text: <>Constante numérica 46 para la tecla delete.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "DIGIT_0",
    title_text: "DIGIT_0",
    text: <>Constante numérica 48 para la tecla digit 0.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "DIGIT_1",
    title_text: "DIGIT_1",
    text: <>Constante numérica 49 para la tecla digit 1.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "DIGIT_2",
    title_text: "DIGIT_2",
    text: <>Constante numérica 50 para la tecla digit 2.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "DIGIT_3",
    title_text: "DIGIT_3",
    text: <>Constante numérica 51 para la tecla digit 3.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "DIGIT_4",
    title_text: "DIGIT_4",
    text: <>Constante numérica 52 para la tecla digit 4.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "DIGIT_5",
    title_text: "DIGIT_5",
    text: <>Constante numérica 53 para la tecla digit 5.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "DIGIT_6",
    title_text: "DIGIT_6",
    text: <>Constante numérica 54 para la tecla digit 6.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "DIGIT_7",
    title_text: "DIGIT_7",
    text: <>Constante numérica 55 para la tecla digit 7.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "DIGIT_8",
    title_text: "DIGIT_8",
    text: <>Constante numérica 56 para la tecla digit 8.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "DIGIT_9",
    title_text: "DIGIT_9",
    text: <>Constante numérica 57 para la tecla digit 9.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "A_UPPER",
    title_text: "A_UPPER",
    text: <>Constante numérica 65 para la tecla a upper.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "B_UPPER",
    title_text: "B_UPPER",
    text: <>Constante numérica 66 para la tecla b upper.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "C_UPPER",
    title_text: "C_UPPER",
    text: <>Constante numérica 67 para la tecla c upper.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "D_UPPER",
    title_text: "D_UPPER",
    text: <>Constante numérica 68 para la tecla d upper.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "E_UPPER",
    title_text: "E_UPPER",
    text: <>Constante numérica 69 para la tecla e upper.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "F_UPPER",
    title_text: "F_UPPER",
    text: <>Constante numérica 70 para la tecla f upper.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "G_UPPER",
    title_text: "G_UPPER",
    text: <>Constante numérica 71 para la tecla g upper.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "H_UPPER",
    title_text: "H_UPPER",
    text: <>Constante numérica 72 para la tecla h upper.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "I_UPPER",
    title_text: "I_UPPER",
    text: <>Constante numérica 73 para la tecla i upper.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "J_UPPER",
    title_text: "J_UPPER",
    text: <>Constante numérica 74 para la tecla j upper.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "K_UPPER",
    title_text: "K_UPPER",
    text: <>Constante numérica 75 para la tecla k upper.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "L_UPPER",
    title_text: "L_UPPER",
    text: <>Constante numérica 76 para la tecla l upper.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "M_UPPER",
    title_text: "M_UPPER",
    text: <>Constante numérica 77 para la tecla m upper.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "N_UPPER",
    title_text: "N_UPPER",
    text: <>Constante numérica 78 para la tecla n upper.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "O_UPPER",
    title_text: "O_UPPER",
    text: <>Constante numérica 79 para la tecla o upper.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "P_UPPER",
    title_text: "P_UPPER",
    text: <>Constante numérica 80 para la tecla p upper.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "Q_UPPER",
    title_text: "Q_UPPER",
    text: <>Constante numérica 81 para la tecla q upper.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "R_UPPER",
    title_text: "R_UPPER",
    text: <>Constante numérica 82 para la tecla r upper.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "S_UPPER",
    title_text: "S_UPPER",
    text: <>Constante numérica 83 para la tecla s upper.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "T_UPPER",
    title_text: "T_UPPER",
    text: <>Constante numérica 84 para la tecla t upper.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "U_UPPER",
    title_text: "U_UPPER",
    text: <>Constante numérica 85 para la tecla u upper.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "V_UPPER",
    title_text: "V_UPPER",
    text: <>Constante numérica 86 para la tecla v upper.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "W_UPPER",
    title_text: "W_UPPER",
    text: <>Constante numérica 87 para la tecla w upper.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "X_UPPER",
    title_text: "X_UPPER",
    text: <>Constante numérica 88 para la tecla x upper.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "Y_UPPER",
    title_text: "Y_UPPER",
    text: <>Constante numérica 89 para la tecla y upper.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "Z_UPPER",
    title_text: "Z_UPPER",
    text: <>Constante numérica 90 para la tecla z upper.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "A_LOWER",
    title_text: "A_LOWER",
    text: <>Constante numérica 97 para la tecla a lower.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "B_LOWER",
    title_text: "B_LOWER",
    text: <>Constante numérica 98 para la tecla b lower.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "C_LOWER",
    title_text: "C_LOWER",
    text: <>Constante numérica 99 para la tecla c lower.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "D_LOWER",
    title_text: "D_LOWER",
    text: <>Constante numérica 100 para la tecla d lower.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "E_LOWER",
    title_text: "E_LOWER",
    text: <>Constante numérica 101 para la tecla e lower.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "F_LOWER",
    title_text: "F_LOWER",
    text: <>Constante numérica 102 para la tecla f lower.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "G_LOWER",
    title_text: "G_LOWER",
    text: <>Constante numérica 103 para la tecla g lower.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "H_LOWER",
    title_text: "H_LOWER",
    text: <>Constante numérica 104 para la tecla h lower.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "I_LOWER",
    title_text: "I_LOWER",
    text: <>Constante numérica 105 para la tecla i lower.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "J_LOWER",
    title_text: "J_LOWER",
    text: <>Constante numérica 106 para la tecla j lower.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "K_LOWER",
    title_text: "K_LOWER",
    text: <>Constante numérica 107 para la tecla k lower.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "L_LOWER",
    title_text: "L_LOWER",
    text: <>Constante numérica 108 para la tecla l lower.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "M_LOWER",
    title_text: "M_LOWER",
    text: <>Constante numérica 109 para la tecla m lower.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "N_LOWER",
    title_text: "N_LOWER",
    text: <>Constante numérica 110 para la tecla n lower.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "O_LOWER",
    title_text: "O_LOWER",
    text: <>Constante numérica 111 para la tecla o lower.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "P_LOWER",
    title_text: "P_LOWER",
    text: <>Constante numérica 112 para la tecla p lower.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "Q_LOWER",
    title_text: "Q_LOWER",
    text: <>Constante numérica 113 para la tecla q lower.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "R_LOWER",
    title_text: "R_LOWER",
    text: <>Constante numérica 114 para la tecla r lower.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "S_LOWER",
    title_text: "S_LOWER",
    text: <>Constante numérica 115 para la tecla s lower.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "T_LOWER",
    title_text: "T_LOWER",
    text: <>Constante numérica 116 para la tecla t lower.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "U_LOWER",
    title_text: "U_LOWER",
    text: <>Constante numérica 117 para la tecla u lower.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "V_LOWER",
    title_text: "V_LOWER",
    text: <>Constante numérica 118 para la tecla v lower.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "W_LOWER",
    title_text: "W_LOWER",
    text: <>Constante numérica 119 para la tecla w lower.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "X_LOWER",
    title_text: "X_LOWER",
    text: <>Constante numérica 120 para la tecla x lower.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "Y_LOWER",
    title_text: "Y_LOWER",
    text: <>Constante numérica 121 para la tecla y lower.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "Z_LOWER",
    title_text: "Z_LOWER",
    text: <>Constante numérica 122 para la tecla z lower.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "KEY_A",
    title_text: "KEY_A",
    text: <>Constante numérica 65 para la tecla key a.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "KEY_B",
    title_text: "KEY_B",
    text: <>Constante numérica 66 para la tecla key b.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "KEY_C",
    title_text: "KEY_C",
    text: <>Constante numérica 67 para la tecla key c.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "KEY_D",
    title_text: "KEY_D",
    text: <>Constante numérica 68 para la tecla key d.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "KEY_E",
    title_text: "KEY_E",
    text: <>Constante numérica 69 para la tecla key e.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "KEY_F",
    title_text: "KEY_F",
    text: <>Constante numérica 70 para la tecla key f.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "KEY_G",
    title_text: "KEY_G",
    text: <>Constante numérica 71 para la tecla key g.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "KEY_H",
    title_text: "KEY_H",
    text: <>Constante numérica 72 para la tecla key h.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "KEY_I",
    title_text: "KEY_I",
    text: <>Constante numérica 73 para la tecla key i.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "KEY_J",
    title_text: "KEY_J",
    text: <>Constante numérica 74 para la tecla key j.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "KEY_K",
    title_text: "KEY_K",
    text: <>Constante numérica 75 para la tecla key k.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "KEY_L",
    title_text: "KEY_L",
    text: <>Constante numérica 76 para la tecla key l.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "KEY_M",
    title_text: "KEY_M",
    text: <>Constante numérica 77 para la tecla key m.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "KEY_N",
    title_text: "KEY_N",
    text: <>Constante numérica 78 para la tecla key n.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "KEY_O",
    title_text: "KEY_O",
    text: <>Constante numérica 79 para la tecla key o.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "KEY_P",
    title_text: "KEY_P",
    text: <>Constante numérica 80 para la tecla key p.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "KEY_Q",
    title_text: "KEY_Q",
    text: <>Constante numérica 81 para la tecla key q.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "KEY_R",
    title_text: "KEY_R",
    text: <>Constante numérica 82 para la tecla key r.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "KEY_S",
    title_text: "KEY_S",
    text: <>Constante numérica 83 para la tecla key s.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "KEY_T",
    title_text: "KEY_T",
    text: <>Constante numérica 84 para la tecla key t.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "KEY_U",
    title_text: "KEY_U",
    text: <>Constante numérica 85 para la tecla key u.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "KEY_V",
    title_text: "KEY_V",
    text: <>Constante numérica 86 para la tecla key v.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "KEY_W",
    title_text: "KEY_W",
    text: <>Constante numérica 87 para la tecla key w.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "KEY_X",
    title_text: "KEY_X",
    text: <>Constante numérica 88 para la tecla key x.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "KEY_Y",
    title_text: "KEY_Y",
    text: <>Constante numérica 89 para la tecla key y.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "KEY_Z",
    title_text: "KEY_Z",
    text: <>Constante numérica 90 para la tecla key z.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "META_LEFT",
    title_text: "META_LEFT",
    text: <>Constante numérica 91 para la tecla meta left.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "META_RIGHT",
    title_text: "META_RIGHT",
    text: <>Constante numérica 92 para la tecla meta right.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "CONTEXT_MENU",
    title_text: "CONTEXT_MENU",
    text: <>Constante numérica 93 para la tecla context menu.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "NUMPAD_0",
    title_text: "NUMPAD_0",
    text: <>Constante numérica 96 para la tecla numpad 0.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "NUMPAD_1",
    title_text: "NUMPAD_1",
    text: <>Constante numérica 97 para la tecla numpad 1.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "NUMPAD_2",
    title_text: "NUMPAD_2",
    text: <>Constante numérica 98 para la tecla numpad 2.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "NUMPAD_3",
    title_text: "NUMPAD_3",
    text: <>Constante numérica 99 para la tecla numpad 3.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "NUMPAD_4",
    title_text: "NUMPAD_4",
    text: <>Constante numérica 100 para la tecla numpad 4.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "NUMPAD_5",
    title_text: "NUMPAD_5",
    text: <>Constante numérica 101 para la tecla numpad 5.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "NUMPAD_6",
    title_text: "NUMPAD_6",
    text: <>Constante numérica 102 para la tecla numpad 6.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "NUMPAD_7",
    title_text: "NUMPAD_7",
    text: <>Constante numérica 103 para la tecla numpad 7.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "NUMPAD_8",
    title_text: "NUMPAD_8",
    text: <>Constante numérica 104 para la tecla numpad 8.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "NUMPAD_9",
    title_text: "NUMPAD_9",
    text: <>Constante numérica 105 para la tecla numpad 9.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "NUMPAD_MULTIPLY",
    title_text: "NUMPAD_MULTIPLY",
    text: <>Constante numérica 106 para la tecla numpad multiply.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "NUMPAD_ADD",
    title_text: "NUMPAD_ADD",
    text: <>Constante numérica 107 para la tecla numpad add.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "NUMPAD_SEPARATOR",
    title_text: "NUMPAD_SEPARATOR",
    text: <>Constante numérica 108 para la tecla numpad separator.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "NUMPAD_SUBTRACT",
    title_text: "NUMPAD_SUBTRACT",
    text: <>Constante numérica 109 para la tecla numpad subtract.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "NUMPAD_DECIMAL",
    title_text: "NUMPAD_DECIMAL",
    text: <>Constante numérica 110 para la tecla numpad decimal.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "NUMPAD_DIVIDE",
    title_text: "NUMPAD_DIVIDE",
    text: <>Constante numérica 111 para la tecla numpad divide.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "F1",
    title_text: "F1",
    text: <>Constante numérica 112 para la tecla f1.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "F2",
    title_text: "F2",
    text: <>Constante numérica 113 para la tecla f2.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "F3",
    title_text: "F3",
    text: <>Constante numérica 114 para la tecla f3.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "F4",
    title_text: "F4",
    text: <>Constante numérica 115 para la tecla f4.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "F5",
    title_text: "F5",
    text: <>Constante numérica 116 para la tecla f5.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "F6",
    title_text: "F6",
    text: <>Constante numérica 117 para la tecla f6.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "F7",
    title_text: "F7",
    text: <>Constante numérica 118 para la tecla f7.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "F8",
    title_text: "F8",
    text: <>Constante numérica 119 para la tecla f8.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "F9",
    title_text: "F9",
    text: <>Constante numérica 120 para la tecla f9.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "F10",
    title_text: "F10",
    text: <>Constante numérica 121 para la tecla f10.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "F11",
    title_text: "F11",
    text: <>Constante numérica 122 para la tecla f11.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "F12",
    title_text: "F12",
    text: <>Constante numérica 123 para la tecla f12.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "NUM_LOCK",
    title_text: "NUM_LOCK",
    text: <>Constante numérica 144 para la tecla num lock.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "SCROLL_LOCK",
    title_text: "SCROLL_LOCK",
    text: <>Constante numérica 145 para la tecla scroll lock.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "SEMICOLON",
    title_text: "SEMICOLON",
    text: <>Constante numérica 186 para la tecla semicolon.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "EQUAL",
    title_text: "EQUAL",
    text: <>Constante numérica 187 para la tecla equal.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "COMMA",
    title_text: "COMMA",
    text: <>Constante numérica 188 para la tecla comma.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "DASH",
    title_text: "DASH",
    text: <>Constante numérica 189 para la tecla dash.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "PERIOD",
    title_text: "PERIOD",
    text: <>Constante numérica 190 para la tecla period.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "SLASH",
    title_text: "SLASH",
    text: <>Constante numérica 191 para la tecla slash.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "GRAVE",
    title_text: "GRAVE",
    text: <>Constante numérica 192 para la tecla grave.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "BRACKET_LEFT",
    title_text: "BRACKET_LEFT",
    text: <>Constante numérica 219 para la tecla bracket left.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "BACKSLASH",
    title_text: "BACKSLASH",
    text: <>Constante numérica 220 para la tecla backslash.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "BRACKET_RIGHT",
    title_text: "BRACKET_RIGHT",
    text: <>Constante numérica 221 para la tecla bracket right.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "QUOTE",
    title_text: "QUOTE",
    text: <>Constante numérica 222 para la tecla quote.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "MOUSE_LEFT",
    title_text: "MOUSE_LEFT",
    text: <>Constante numérica 0 para la tecla mouse left.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "MOUSE_MIDDLE",
    title_text: "MOUSE_MIDDLE",
    text: <>Constante numérica 1 para la tecla mouse middle.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
  {
    title: "MOUSE_RIGHT",
    title_text: "MOUSE_RIGHT",
    text: <>Constante numérica 2 para la tecla mouse right.</>,
    button_text: "Cerrar",
    variant: "body1",
  },
];
